const list = [
    {
      id: 1,
      title: "Wrist Watch",
      author: "boAt Xtend Smart Watch with Alexa Built-in,",
      price: 89,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41lQan54SPL._AC_SR400,600_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Shoes",
      author: "TRACER Men's Scoosh-2705 Sneakers",
      price: 98,
      img: "https://images-eu.ssl-images-amazon.com/images/I/617l3JNkTrL._AC_UL160_SR160,160_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Wrist Watch",
      author: "boAt Xtend Smart Watch with Alexa Built-in,",
      price: 143,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41lQan54SPL._AC_SR400,600_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Shoes",
      author: "TRACER Men's Scoosh-2705 Sneakers",
      price: 57,
      img: "https://images-eu.ssl-images-amazon.com/images/I/617l3JNkTrL._AC_UL160_SR160,160_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Wrist Watch",
      author: "boAt Xtend Smart Watch with Alexa Built-in,",
      price: 149,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41lQan54SPL._AC_SR400,600_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Shoes",
      author: "TRACER Men's Scoosh-2705 Sneakers",
      price: 135,
      img: "https://images-eu.ssl-images-amazon.com/images/I/617l3JNkTrL._AC_UL160_SR160,160_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Wrist Watch",
      author: "boAt Xtend Smart Watch with Alexa Built-in,",
      price: 693,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41lQan54SPL._AC_SR400,600_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Shoes",
      author: "TRACER Men's Scoosh-2705 Sneakers",
      price: 289,
      img: "https://images-eu.ssl-images-amazon.com/images/I/617l3JNkTrL._AC_UL160_SR160,160_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Wrist Watch",
      author: "boAt Xtend Smart Watch with Alexa Built-in,",
      price: 80,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41lQan54SPL._AC_SR400,600_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Shoes",
      author: "TRACER Men's Scoosh-2705 Sneakers",
      price: 86,
      img: "https://images-eu.ssl-images-amazon.com/images/I/617l3JNkTrL._AC_UL160_SR160,160_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Wrist Watch",
      author: "boAt Xtend Smart Watch with Alexa Built-in,",
      price: 120,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41lQan54SPL._AC_SR400,600_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Shoes",
      author: "TRACER Men's Scoosh-2705 Sneakers",
      price: 157,
      img: "https://images-eu.ssl-images-amazon.com/images/I/617l3JNkTrL._AC_UL160_SR160,160_.jpg",
      amount: 1,
    },
  ];
  
  export default list;